---
title: "20211029 Rewriting functions"
author: "cheungngo"
date: "29 October 2021"
output: html_document
---

```{r}
library(readxl)
uni_students <- read_excel("~/unrest_covid_mental/data/uni_students.xlsx")
```


### Serial logistic regression for continuous variables

```{r}
log_reg_spss_cont0 = function(datay, datax, j, i) {
  var = as.numeric(unlist(datax[,i]))
  dep = as.numeric(unlist(datay[,j]))
  ind = which(!is.na(var))
  var = var[ind]
  dep = dep[ind]
  coeff = matrix(ncol = 4)
  modglm = glm(dep~var, family = "binomial")
  coeff[1,] = summary(modglm)$coef[2,]
  rownames(coeff) = colnames(datax)[i]
  colnames(coeff) = c("Estimate", "SD", "z-value", "p-value")
  coeff = round(coeff, digits = 3)
  return(coeff)
}

cont_beau = function(cont) {
  OR = apply(cont, 1, function (i) {
    exp(i[1] + qnorm(c(0.025,0.5,0.975)) * i[2])
  })
  OR = t(OR)
  OR_b = apply(OR, 1, function (i) {
    if (i[2] != 1) {
      return(paste(round(i[2],2), " (", round(i[1],2), "-", round(i[3],2), ")", sep = ""))
    } else {
      return(1)
    }
  })
  result = as.data.frame(cbind(OR_b, cont[,4]))
  colnames(result) = c("OR","p")
  return(result)
}

log_reg_cont_care4all = function (datay, datax, j, i) {
  for (x in i) {
    assign(paste("mod", colnames(datax)[x],sep = ""),
           log_reg_spss_cont0(datay, datax, j, x))
  }
  tab = eval(parse(text = paste("mod", colnames(datax)[i[1]],sep = "")))
  for (x in i[-1]) {
    tab2 = eval(parse(text = paste("mod", colnames(datax)[x],sep = "")))
    tab = rbind(tab, tab2)
  }
  return(cont_beau(tab))
}
```

```{r}
log_reg_cont_care4all(uni_students, uni_students, 126, c(91,92))
```


### Serial logistic regression for categorical variables

```{r}
OR_CI = function(m) {
  ifelse(is.na(coef(m)[2]),
         return(c(NA,NA,NA)),
         return(exp(summary(m)$coefficients[2,1] +
                      qnorm(c(0.025,0.5,0.975)) * summary(m)$coefficients[2,2])))
}

log_reg_spss_kref_care = function(datay, datax, j, i, kref) {
  var = as.numeric(unlist(datax[,i]))
  dep = as.numeric(unlist(datay[,j]))
  ind = which(!is.na(var))
  var = var[ind]
  dep = dep[ind]
  coeff = matrix(nrow = length(table(var)),
                 ncol = 4)
  coeff[1,] = c(NA,1,NA,NA)
  ref = kref
  level = as.numeric(unlist(levels(as.factor(var))))
  level = level[-which(level==ref)]
  count = 2
  for (k in level) {
    ind2 = which(var==k | var==ref)
    yy = dep[ind2]
    xx = var[ind2]
    modglm = glm(yy~xx, family = "binomial")
    coeff[count,1:3] = OR_CI(modglm)
    ifelse(is.na(coef(modglm)[2]),
           coeff[count,4] <- NA,
           coeff[count,4] <- as.numeric(unlist(summary(modglm)$coefficients[2,4])))
    count = count + 1
  }
  
  var_names = colnames(datax)[i]
  rownames(coeff) = paste(var_names[1], c(ref, level), sep = "_")
  colnames(coeff) = c("LCI", "OR", "UCI", "p-value")
  coeff = round(coeff, digits = 3)
  return(coeff)
}

beautify_cate = function (data) {
  data[,1:3] = apply(data[,1:3], 2, function(i) {
    round(i, digits = 1)
  })
  OR_b = apply(data, 1, function (i) {
    if (i[2] != 1) {
      return(paste(i[2], " (", i[1], "-", i[3], ")", sep = ""))
    } else {
      return(1)
    }
  })
  result = as.data.frame(as.data.frame(cbind(OR_b, data[,4])))
  colnames(result) = c("OR","p")
  return(result)
}

log_reg_cate_care4all = function (datay, datax, j, i, kref) {
  for (x in i) {
    assign(paste("mod", colnames(datax)[x],sep = ""),
           log_reg_spss_kref_care(datay, datax, j, x, kref))
  }
  tab = eval(parse(text = paste("mod", colnames(datax)[i[1]],sep = "")))
  for (x in i[-1]) {
    tab2 = eval(parse(text = paste("mod", colnames(datax)[x],sep = "")))
    tab = rbind(tab, tab2)
  }
  return(beautify_cate(tab))
}
```

```{r}
log_reg_cate_care4all(uni_students, uni_students, 126, 67:70, 0)
```
